### ISSUE TITLE
cnpmjs设置为0时异常

### ISSUE THREAD

**Issue by belier-cn** [hunshcn/gh-proxy#6]
异常信息
```
cfworker error:
TypeError: Cannot read property 'href' of null
    at proxy (worker.js:130:36)
    at httpHandler (worker.js:120:12)
    at fetchHandler (worker.js:73:16)
    at worker.js:49:17
```

**Comment by hunshcn** [comment]
没能够复现，请附上出现问题的url
不过刚刚检查发现代码其他地方出现了问题（虽然应该跟本问题无关），可以尝试一下新版本
